package View;

public class TipsDeAhorro extends javax.swing.JFrame {

    /**
     * Creates new form TipsDeAhorro
     */
    public TipsDeAhorro() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        imagen_01 = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        separador1 = new javax.swing.JLabel();
        tip1 = new javax.swing.JLabel();
        separador2 = new javax.swing.JLabel();
        tip2 = new javax.swing.JLabel();
        separador3 = new javax.swing.JLabel();
        tip3 = new javax.swing.JLabel();
        separador4 = new javax.swing.JLabel();
        tip4 = new javax.swing.JLabel();
        separador5 = new javax.swing.JLabel();
        tip5 = new javax.swing.JLabel();
        separador6 = new javax.swing.JLabel();
        tip6 = new javax.swing.JLabel();
        separador7 = new javax.swing.JLabel();
        tip7 = new javax.swing.JLabel();
        separador8 = new javax.swing.JLabel();
        tip8 = new javax.swing.JLabel();
        separador9 = new javax.swing.JLabel();
        tip9 = new javax.swing.JLabel();
        separador10 = new javax.swing.JLabel();
        tip10 = new javax.swing.JLabel();
        separador11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(196, 218, 250));
        bg.setInheritsPopupMenu(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_01.setBackground(new java.awt.Color(0, 0, 0));
        imagen_01.setForeground(new java.awt.Color(0, 0, 0));
        imagen_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagenProyecto_01.png"))); // NOI18N
        imagen_01.setText("jLabel1");
        bg.add(imagen_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 290));

        inicio.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        inicio.setForeground(new java.awt.Color(0, 0, 0));
        inicio.setText("ESTOS TIPS SON PARA MEJORAR EL CONSUMO DE SU ENERGIA:");
        bg.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 410, 20));

        separador1.setForeground(new java.awt.Color(0, 0, 0));
        separador1.setText("========================================================================");
        bg.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 580, 20));

        tip1.setForeground(new java.awt.Color(0, 0, 0));
        tip1.setText("1.  Evitar que los niños jueguen con las conexiones eléctricas. ");
        bg.add(tip1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 510, 20));

        separador2.setForeground(new java.awt.Color(0, 0, 0));
        separador2.setText("========================================================================");
        bg.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 580, 20));

        tip2.setForeground(new java.awt.Color(0, 0, 0));
        tip2.setText("2.  Renueva tus electrodomésticos por unos más eficientes. Ahorrar energía, ahorrar dinero. ");
        bg.add(tip2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 570, 20));

        separador3.setForeground(new java.awt.Color(0, 0, 0));
        separador3.setText("========================================================================");
        bg.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 580, 20));

        tip3.setForeground(new java.awt.Color(0, 0, 0));
        tip3.setText("3.  Mientras tenga luz solar no encienda las bombillas. ");
        bg.add(tip3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 570, 20));

        separador4.setForeground(new java.awt.Color(0, 0, 0));
        separador4.setText("========================================================================");
        bg.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 580, 20));

        tip4.setForeground(new java.awt.Color(0, 0, 0));
        tip4.setText("4.  Pinta tu casa con colores claros para favorecer la iluminación de tu hogar.");
        bg.add(tip4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 570, 20));

        separador5.setForeground(new java.awt.Color(0, 0, 0));
        separador5.setText("========================================================================");
        bg.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 580, 20));

        tip5.setForeground(new java.awt.Color(0, 0, 0));
        tip5.setText("5.  Apaga y desconecta los equipos electrónicos antes de moverlos del lugar. ");
        bg.add(tip5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 570, 20));

        separador6.setForeground(new java.awt.Color(0, 0, 0));
        separador6.setText("========================================================================");
        bg.add(separador6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 580, 20));

        tip6.setForeground(new java.awt.Color(0, 0, 0));
        tip6.setText("6.  Desconecta los cargadores de los dispositivos electrónicos que no esté usando. ");
        bg.add(tip6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 570, 20));

        separador7.setForeground(new java.awt.Color(0, 0, 0));
        separador7.setText("========================================================================");
        bg.add(separador7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 580, 20));

        tip7.setForeground(new java.awt.Color(0, 0, 0));
        tip7.setText("7.  Usa bombillas LED. Con esto puede ahorrar el consumo de energía. ");
        bg.add(tip7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 570, 20));

        separador8.setForeground(new java.awt.Color(0, 0, 0));
        separador8.setText("========================================================================");
        bg.add(separador8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 580, 20));

        tip8.setForeground(new java.awt.Color(0, 0, 0));
        tip8.setText("8.  Limpia el refrigerador y el aire acondicionado para mejorar su eficiencia. ");
        bg.add(tip8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 570, 20));

        separador9.setForeground(new java.awt.Color(0, 0, 0));
        separador9.setText("========================================================================");
        bg.add(separador9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 580, 20));

        tip9.setForeground(new java.awt.Color(0, 0, 0));
        tip9.setText("9.  Cierra bien la nevera para que no gaste más energía. ");
        bg.add(tip9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 570, 20));

        separador10.setForeground(new java.awt.Color(0, 0, 0));
        separador10.setText("========================================================================");
        bg.add(separador10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 580, 20));

        tip10.setForeground(new java.awt.Color(0, 0, 0));
        tip10.setText("10. Apaga el computador si no lo vas a usar por un buen rato.");
        bg.add(tip10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 570, 20));

        separador11.setForeground(new java.awt.Color(0, 0, 0));
        separador11.setText("========================================================================");
        bg.add(separador11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 580, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel imagen_01;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel separador1;
    private javax.swing.JLabel separador10;
    private javax.swing.JLabel separador11;
    private javax.swing.JLabel separador2;
    private javax.swing.JLabel separador3;
    private javax.swing.JLabel separador4;
    private javax.swing.JLabel separador5;
    private javax.swing.JLabel separador6;
    private javax.swing.JLabel separador7;
    private javax.swing.JLabel separador8;
    private javax.swing.JLabel separador9;
    private javax.swing.JLabel tip1;
    private javax.swing.JLabel tip10;
    private javax.swing.JLabel tip2;
    private javax.swing.JLabel tip3;
    private javax.swing.JLabel tip4;
    private javax.swing.JLabel tip5;
    private javax.swing.JLabel tip6;
    private javax.swing.JLabel tip7;
    private javax.swing.JLabel tip8;
    private javax.swing.JLabel tip9;
    // End of variables declaration//GEN-END:variables
}
