package View;

import Model.Factura;
import Controller.FacturaController;
import Controller.UsuarioController;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JLabel;

public class ProcesoDeFactura extends javax.swing.JFrame {

    UsuarioController controller = new UsuarioController("", 0, 0, 0);
    FacturaController controller2 = new FacturaController(0, 0);
    private String nombre;

    public ProcesoDeFactura() {
        initComponents();
        setLocationRelativeTo(null);
        jLabelMostrarUsuario.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonTipsDeAhorro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelMostrarUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldHorasConsumo = new javax.swing.JTextField();
        jButtonDocumento = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jLabelArchivoCreado = new javax.swing.JLabel();
        jLabelUbicacionArchivo = new javax.swing.JLabel();
        jButtonGuardarInfo = new javax.swing.JButton();
        jLabelMensajeHoras = new javax.swing.JLabel();
        jLabelInfoConsumo = new javax.swing.JLabel();
        jLabelError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(196, 218, 250));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(77, 130, 188));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(196, 218, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("PROCESO DE FACTURA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 80));

        jPanel4.setBackground(new java.awt.Color(196, 218, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setForeground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonTipsDeAhorro.setBackground(new java.awt.Color(77, 130, 188));
        jButtonTipsDeAhorro.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonTipsDeAhorro.setForeground(new java.awt.Color(0, 0, 0));
        jButtonTipsDeAhorro.setText("TIPS DE AHORRO");
        jButtonTipsDeAhorro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipsDeAhorroActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonTipsDeAhorro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 130, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("USUARIO:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jLabelMostrarUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jLabelMostrarUsuario.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabelMostrarUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelMostrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 70, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INGRESE LAS HORAS QUE CONSUMIO EN EL MES: ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jTextFieldHorasConsumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasConsumoActionPerformed(evt);
            }
        });
        jPanel4.add(jTextFieldHorasConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, -1));

        jButtonDocumento.setBackground(new java.awt.Color(77, 130, 188));
        jButtonDocumento.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonDocumento.setForeground(new java.awt.Color(0, 0, 0));
        jButtonDocumento.setText("CREAR DOCUMENTO.TXT");
        jButtonDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDocumentoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 180, -1));

        jButtonCerrar.setBackground(new java.awt.Color(77, 130, 188));
        jButtonCerrar.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonCerrar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCerrar.setText("CERRAR");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabelArchivoCreado.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelArchivoCreado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 20));

        jLabelUbicacionArchivo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelUbicacionArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 10));

        jButtonGuardarInfo.setBackground(new java.awt.Color(77, 130, 188));
        jButtonGuardarInfo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        jButtonGuardarInfo.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGuardarInfo.setText("GUARDAR");
        jButtonGuardarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarInfoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonGuardarInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabelMensajeHoras.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelMensajeHoras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 190, 20));

        jLabelInfoConsumo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelInfoConsumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 360, 10));

        jLabelError.setForeground(new java.awt.Color(0, 0, 0));
        jPanel4.add(jLabelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 420, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHorasConsumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasConsumoActionPerformed
        // TODO add your handling code here:
        try {
            int horas = Integer.parseInt(jTextFieldHorasConsumo.getText().trim());
            controller2.getHorasConsumo();
        } catch (NumberFormatException e) {
            jLabelMensajeHoras.setText("Por favor ingrese un número válido de horas.");
        }
    }//GEN-LAST:event_jTextFieldHorasConsumoActionPerformed

    private void jButtonTipsDeAhorroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipsDeAhorroActionPerformed
        // TODO add your handling code here:
        TipsDeAhorro mensaje = new TipsDeAhorro();
        mensaje.setVisible(true);
    }//GEN-LAST:event_jButtonTipsDeAhorroActionPerformed

    private void jButtonDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDocumentoActionPerformed
        // TODO add your handling code here:
        try {
            File archivo = new File("factura_usuario.txt");
            FileWriter escritorArchivo = new FileWriter(archivo);
            PrintWriter escritor = new PrintWriter(escritorArchivo);

            String nombre = controller.getNombre();
            int edad = controller.getEdad();
            int identificacion = controller.getIdentificacion();
            int estrato = controller.getEstrato();
            int horas = controller2.getHorasConsumo();
            double valorKWH = controller2.getValorKWH();

            escritor.println("NOMBRE: " + nombre);
            escritor.println("EDAD: " + edad);
            escritor.println("IDENTIFICACION: " + identificacion);
            escritor.println("ESTRATO: " + estrato);
            escritor.println("HORAS DE CONSUMO: " + horas);
            escritor.println("VALOR TOTAL FACTURA: " + valorKWH);
            escritor.close();

            jLabelUbicacionArchivo.setText("Archivo creado: " + archivo.getAbsolutePath());

        } catch (IOException e) {
            jLabelUbicacionArchivo.setText("Error al crear el archivo.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonDocumentoActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonGuardarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarInfoActionPerformed
        // TODO add your handling code here:
        try {
            int horas = Integer.parseInt(jTextFieldHorasConsumo.getText().trim());
            controller2.setHorasConsumo(horas);
            controller2.procesoFactura(controller.getEstrato());
            jLabelArchivoCreado.setText("Información guardada correctamente.");
            jLabelInfoConsumo.setText("El valor total de las horas consumidas es: $" + controller2.getValorKWH());
        } catch (NumberFormatException e) {
            jLabelMensajeHoras.setText("Por favor ingrese un número válido de horas.");
        }




    }//GEN-LAST:event_jButtonGuardarInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonDocumento;
    private javax.swing.JButton jButtonGuardarInfo;
    private javax.swing.JButton jButtonTipsDeAhorro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelArchivoCreado;
    private javax.swing.JLabel jLabelError;
    private javax.swing.JLabel jLabelInfoConsumo;
    private javax.swing.JLabel jLabelMensajeHoras;
    private javax.swing.JLabel jLabelMostrarUsuario;
    private javax.swing.JLabel jLabelUbicacionArchivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextFieldHorasConsumo;
    // End of variables declaration//GEN-END:variables
}
